import type { Chapter, Idea, RouteSegment, Stop, Waypoint } from "./types";

/**
 * THE ITINERARY. Edit this file to change dates, stops, rides or copy.
 * Source: BikeAsia custom tour brief + route-planner profiles (distances and climbing per day).
 * Coordinates: OpenStreetMap (Nominatim / Overpass), checked Sept 2026.
 * Route lines are regenerated by `npm run build:routes`: rail from OSM railway relations,
 * rides and transfers from the OSRM road router (the drawn line is the road alignment, approx.;
 * the km and climbing shown are the planner's figures, `rideKm` / `climbM`).
 */

export const TRIP = {
  title: "China Cycle Adventure",
  start: "2026-10-10",
  end: "2026-10-19",
  arrival: "guiyang",
  departure: "yangshuo",
  travellers: "Kieran & friends",
  strap: "Eight days by bike from the Miao and Dong villages of Guizhou to the rice terraces and karst peaks of Guangxi.",
  /** planner totals (the image of the brief); the map draws the road alignment */
  totals: { km: 508, climbM: 7240, ridingDays: 8, days: 10 },
  operator: "BikeAsia custom tour",
};

export const CHAPTERS: Chapter[] = [
  { id: "guizhou", numeral: "I", title: "Guizhou · Miao & Dong country", label: { lon: 108.35, lat: 26.75 } },
  { id: "guangxi", numeral: "II", title: "Guangxi · terraces & karst", label: { lon: 110.75, lat: 25.55 } },
];

const OSM = "OpenStreetMap place node";

export const STOPS: Stop[] = [
  {
    id: "guiyang", number: 1, chapter: "guizhou",
    dateStart: "2026-10-10", dateEnd: "2026-10-10",
    city: "Guiyang", chineseName: "贵阳", region: "Guizhou", regionZh: "贵州",
    longitude: 106.7088, latitude: 26.5876, confidence: "verified", coordSource: "OSM, Penshuichi (city centre)",
    kicker: "Arrival & group meeting",
    highlights: ["Arrive 18:00, airport pickup", "Meet the group", "Welcome dinner"],
    icon: "city",
  },
  {
    id: "baiyan", number: 2, chapter: "guizhou",
    dateStart: "2026-10-11", dateEnd: "2026-10-11",
    city: "Baiyan Village", chineseName: "白岩村", locality: "雷山县 Leishan · 黔东南 Qiandongnan",
    region: "Guizhou", regionZh: "贵州",
    longitude: 108.14, latitude: 26.355, confidence: "approximate",
    coordSource: "Not mapped in OSM; placed ~8.5 km SE of Leishan town, south of Wudong village (county gazetteer)",
    kicker: "Miao village under Leigong Shan",
    highlights: ["Bullet train Guiyang → Kaili (35 min)", "50 km along a stream valley", "Gentle 5 km climb up Leigong Shan", "Terraced Miao village"],
    icon: "terraces",
  },
  {
    id: "leli", number: 3, chapter: "guizhou",
    dateStart: "2026-10-12", dateEnd: "2026-10-12",
    city: "Leli", chineseName: "乐里镇", locality: "榕江县 Rongjiang",
    region: "Guizhou", regionZh: "贵州",
    longitude: 108.409, latitude: 26.2256, confidence: "verified", coordSource: `${OSM} (Leli town)`,
    kicker: "Over the top of the ride",
    highlights: ["Highest point of the tour, ~1,800 m", "10 km climb, then a 26 km descent", "Buffalo fighting ring"],
    icon: "peak",
    bigMoment: "Summit",
  },
  {
    id: "dalidong", number: 4, chapter: "guizhou",
    dateStart: "2026-10-13", dateEnd: "2026-10-13",
    city: "Dali Dong Village", chineseName: "大利侗寨", locality: "榕江县 Rongjiang",
    region: "Guizhou", regionZh: "贵州",
    longitude: 108.6394, latitude: 26.0415, confidence: "verified", coordSource: `${OSM} (大利侗寨)`,
    kicker: "Dong village, on foot at the end",
    highlights: ["32 km down the Leli River", "Two climbs and a steep finish", "30 min walk into the village"],
    icon: "drum",
  },
  {
    id: "congjiang", number: 5, chapter: "guizhou",
    dateStart: "2026-10-14", dateEnd: "2026-10-14",
    city: "Congjiang", chineseName: "从江", region: "Guizhou", regionZh: "贵州",
    longitude: 108.9013, latitude: 25.7573, confidence: "verified", coordSource: `${OSM} (county town)`,
    kicker: "Longest but easiest",
    highlights: ["104 km, the longest day", "All the climbing in the first 10 km", "Then down the Duliu River"],
    icon: "river",
  },
  {
    id: "zhaoxing", number: 6, chapter: "guizhou",
    dateStart: "2026-10-15", dateEnd: "2026-10-15",
    city: "Zhaoxing", chineseName: "肇兴侗寨", locality: "黎平县 Liping",
    region: "Guizhou", regionZh: "贵州",
    longitude: 109.176, latitude: 25.9098, confidence: "verified", coordSource: `${OSM} (Zhaoxing village)`,
    kicker: "Eight drum towers",
    highlights: ["Steep 8 km climb, then ridge-lines", "Lunch at Huanggang 黄岗", "Zhaoxing Dong village and its drum towers"],
    icon: "drum",
    bigMoment: "Dong",
  },
  {
    id: "longji", number: 7, chapter: "guangxi",
    dateStart: "2026-10-16", dateEnd: "2026-10-16",
    city: "Longji Terraces", chineseName: "龙脊梯田", locality: "龙胜 Longsheng",
    region: "Guangxi", regionZh: "广西",
    longitude: 110.1211, latitude: 25.7589, confidence: "approximate",
    coordSource: "OSM node for Ping'an village (平安村); the guesthouse itself isn't named in the brief",
    kicker: "The hardest day",
    highlights: ["Transfer to Sishui (1.5–2 hrs)", "One continuous HC climb, 3.88% average", "1 hr hike up to the guesthouse", "Rice terraces"],
    icon: "terraces",
    bigMoment: "HC climb",
  },
  {
    id: "daxu", number: 8, chapter: "guangxi",
    dateStart: "2026-10-17", dateEnd: "2026-10-17",
    city: "Daxu", chineseName: "大圩古镇", locality: "桂林 Guilin",
    region: "Guangxi", regionZh: "广西",
    longitude: 110.4224, latitude: 25.1891, confidence: "verified", coordSource: `${OSM} (Daxu town)`,
    kicker: "Old town on the Li River",
    highlights: ["6 km switchback descent", "One 12 km climb", "Guilin rice noodle lunch", "Transfer from Lingui to Daxu"],
    icon: "river",
  },
  {
    id: "yangshuo", number: 9, chapter: "guangxi",
    dateStart: "2026-10-18", dateEnd: "2026-10-19",
    city: "Yangshuo", chineseName: "阳朔", locality: "旧县村 Jiuxian old town",
    region: "Guangxi", regionZh: "广西",
    longitude: 110.4264, latitude: 24.7885, confidence: "verified", coordSource: `${OSM} (Jiuxian village)`,
    kicker: "Karst country, the finish",
    highlights: ["Li River bike path", "Karst country", "Last night in Jiuxian old town", "19 Oct: transfer to Guilin airport (~1 hr)"],
    icon: "karst",
    bigMoment: "Finish",
  },
];

/** Stations & transfer points (OSM nodes). */
export const WAYPOINTS: Waypoint[] = [
  { id: "guiyang-north", name: "Guiyang North", chineseName: "贵阳北", longitude: 106.6725, latitude: 26.6228, confidence: "verified", coordSource: "OSM station", kind: "station" },
  { id: "kaili-south", name: "Kaili South", chineseName: "凯里南", longitude: 107.8838, latitude: 26.5177, confidence: "verified", coordSource: "OSM station", kind: "station" },
  { id: "sishui", name: "Sishui", chineseName: "泗水乡", longitude: 110.0887, latitude: 25.8606, confidence: "verified", coordSource: "OSM place node", kind: "transfer" },
  { id: "lingui", name: "Lingui", chineseName: "临桂", longitude: 110.2078, latitude: 25.2419, confidence: "approximate", coordSource: "OSM place node for Lingui district; the exact end of the ride isn't in the brief", kind: "transfer" },
  { id: "guilin-airport", name: "Guilin airport", chineseName: "桂林两江机场", longitude: 110.044, latitude: 25.2222, confidence: "verified", coordSource: "OSM aerodrome", kind: "transfer" },
];

/** OSM railway line relations (route=railway), see scripts/build-routes.ts */
export const LINES = {
  huKunHSR: 10627959, // 沪昆高速线 Shanghai–Kunming high-speed
  links: [14650524, 19421724, 19421725, 19421730, 11286955, 10747024], // 联络线 junction links
};

export const SEGMENTS: RouteSegment[] = [
  {
    id: "guiyang-kaili", from: "guiyang-north", to: "kaili-south", mode: "rail", leg: "baiyan", date: "2026-10-11",
    transport: "Bullet train to Kaili (35 min)", serviceStatus: "planned",
    notes: "Drawn from Guiyang North on the Shanghai–Kunming high-speed line; the departure station isn't in the brief.",
    osmLines: [LINES.huKunHSR, ...LINES.links],
  },
  {
    id: "d2", from: "kaili-south", to: "baiyan", mode: "bike", leg: "baiyan", date: "2026-10-11", day: 2,
    transport: "Kaili to Baiyan", rideKm: 60.7, climbM: 911, serviceStatus: "planned",
    notes: "Stream valley for 50 km, then a gentle 5 km climb up Leigong Shan.",
  },
  {
    id: "d3", from: "baiyan", to: "leli", mode: "bike", leg: "leli", date: "2026-10-12", day: 3,
    transport: "Baiyan to Leli", rideKm: 72.7, climbM: 1199, serviceStatus: "planned",
    notes: "Highest point ~1,800 m: a 10 km climb, then a 26 km descent.",
  },
  {
    id: "d4", from: "leli", to: "dalidong", mode: "bike", leg: "dalidong", date: "2026-10-13", day: 4,
    transport: "Leli to Dali Dong village", rideKm: 79.5, climbM: 875, serviceStatus: "planned",
    notes: "32 km down the Leli River, then two climbs and a steep finish. 30 min walk into the village.",
  },
  {
    id: "d5", from: "dalidong", to: "congjiang", mode: "bike", leg: "congjiang", date: "2026-10-14", day: 5,
    transport: "Dali Dong village to Congjiang", rideKm: 104.1, climbM: 548, serviceStatus: "planned",
    notes: "Longest but easiest. All the climbing is in the first 10 km, then the Duliu River.",
  },
  {
    id: "d6", from: "congjiang", to: "zhaoxing", mode: "bike", leg: "zhaoxing", date: "2026-10-15", day: 6,
    transport: "Congjiang to Zhaoxing", rideKm: 55.6, climbM: 1120, serviceStatus: "planned",
    notes: "Steep 8 km climb, ridge-lines, lunch at Huanggang.",
  },
  {
    id: "zhaoxing-sishui", from: "zhaoxing", to: "sishui", mode: "local", leg: "longji", date: "2026-10-16",
    transport: "Transfer to Sishui (1.5–2 hrs)", serviceStatus: "planned",
  },
  {
    id: "d7", from: "sishui", to: "longji", mode: "bike", leg: "longji", date: "2026-10-16", day: 7,
    transport: "Sishui to the Longji terraces", rideKm: 30.7, climbM: 1193, serviceStatus: "planned",
    notes: "Hardest day: one continuous HC climb at 3.88% average, then a 1 hr hike to the guesthouse.",
  },
  {
    id: "d8", from: "longji", to: "lingui", mode: "bike", leg: "daxu", date: "2026-10-17", day: 8,
    transport: "Longji to Lingui", rideKm: 53.5, climbM: 707, serviceStatus: "planned",
    notes: "6 km switchback descent and one 12 km climb. Line drawn to Lingui town; the ride may finish sooner.",
  },
  {
    id: "lingui-daxu", from: "lingui", to: "daxu", mode: "local", leg: "daxu", date: "2026-10-17",
    transport: "Transfer to Daxu old town", serviceStatus: "planned",
  },
  {
    id: "d9", from: "daxu", to: "yangshuo", mode: "bike", leg: "yangshuo", date: "2026-10-18", day: 9,
    transport: "Daxu to Yangshuo", rideKm: 51.1, climbM: 683, serviceStatus: "planned",
    notes: "Li River bike path, then karst country. Last night in Jiuxian old town.",
  },
];

/** No "maybe" places on this trip: the route is fixed. */
export const IDEAS: Idea[] = [];

/** Faint reference cities for orientation only — not part of the route. */
export const CONTEXT_CITIES = [
  { name: "Kaili", zh: "凯里", lon: 107.9812, lat: 26.5663 },
  { name: "Guilin", zh: "桂林", lon: 110.2903, lat: 25.2736 },
  { name: "Liuzhou", zh: "柳州", lon: 109.4155, lat: 24.3255 },
  { name: "Nanning", zh: "南宁", lon: 108.3661, lat: 22.8172 },
  { name: "Kunming", zh: "昆明", lon: 102.7169, lat: 25.0399 },
  { name: "Chongqing", zh: "重庆", lon: 106.5479, lat: 29.5657 },
  { name: "Guangzhou", zh: "广州", lon: 113.2644, lat: 23.1291 },
  { name: "Hong Kong", zh: "香港", lon: 114.1694, lat: 22.3193 },
];

/** Physical-geography labels (anchors placed by hand; Leigong Shan peak from OSM). */
export const PHYSICAL_LABELS = [
  { name: "Leigong Shan", sub: "2,178 m", lon: 108.2026, lat: 26.3872, size: 1 },
  { name: "Yungui Plateau", lon: 105.2, lat: 25.9, size: 2 },
  { name: "Miao Ling", lon: 107.6, lat: 26.2, size: 1 },
  { name: "Li River", lon: 110.52, lat: 24.98, size: 1 },
  { name: "Duliu River", lon: 108.62, lat: 25.86, size: 1 },
  { name: "Sichuan Basin", lon: 105.9, lat: 30.3, size: 2 },
  { name: "Nan Ling", lon: 112.4, lat: 25.2, size: 2 },
];
